baidubce/bce-qianfan-sdk

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/custom.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md

- Add issue template
- Add pr template

Chore GitHub stuff

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/custom.yml
.github/ISSUE_TEMPLATE/feature_request.yml

- **Description:** fix issue template 
* fix bug_report & feature_request
* add custom emoji

fix: issue template

---

src/qianfan/__init__.py
src/qianfan/consts.py
src/qianfan/resources/api_requestor.py
src/qianfan/resources/llm/prompt.py
src/qianfan/resources/llm/utils.py
src/qianfan/resources/tools/prompt.py
src/qianfan/resources/tools/utils.py
src/qianfan/tests/prompt_test.py
src/qianfan/tests/utils/mock_server.py
src/qianfan/tests/utils/utils.py
src/qianfan/utils/__init__.py
src/qianfan/utils/utils.py

- **Description:** support render prompt template api, 
- **Issue:** #13 ,
- **Dependencies:** none,
- **Tag maintainer:** @danielhjz .

feat: Add support for render prompt template api

---

src/qianfan/resources/llm/completion.py

The problem caused the call 4.0 API to report an error.
Please help out,thanks

Update completion.py [ change api path] 🐛 

---

.readthedocs.yaml
Makefile
src/qianfan/docs/quickstart.rst
src/qianfan/docs/root_doc.rst_t
src/scripts/build_doc.sh

doc: add quickstart

---

cookbook/function_call_agent.ipynb

add function_call_agent.ipynb

---

cookbook/console-finetune/console-finetune.ipynb

- **Description:** a patch for console-cookbook
- **Tag maintainer:** for a quicker response, please @stonekim

fix: add console deploy -> done status cell

---

pyproject.toml
src/qianfan/resources/llm/chat_completion.py
src/qianfan/resources/llm/completion.py

feat: supported model=`ERNIE-Bot-8k` in chat and completion.
chore: update ->0.1.2

feat: add model eb8k supported and update version->0.1.2

---

README.md
pyproject.toml
src/qianfan/consts.py
src/qianfan/resources/tools/tokenizer.py
src/qianfan/resources/typing.py
src/qianfan/tests/tokenizer_test.py
src/qianfan/tests/utils/mock_server.py

- **Description:** support tokenizer api
- **Issue:** #51 
- **Dependencies:** None

feat: support tokenizer api

---

src/qianfan/resources/llm/chat_completion.py
src/qianfan/resources/llm/completion.py

- **Description:** update model supported hyperparams, especially for the OpenSource Models
- **Issue:** #51 
- **Tag maintainer:**  @stonekim

feat: update supported params for default models

---

src/qianfan/consts.py
src/qianfan/resources/llm/chat_completion.py
src/qianfan/tests/chat_completion_test.py
src/qianfan/tests/utils/mock_server.py

- **Description:** support concat truncated message param
- **Issue:** #51 
@stonekim PTAL

feat: support auto_concat_truncated messages

---

docs/dataset.md
src/qianfan/resources/console/consts.py
src/qianfan/resources/console/data.py
src/qianfan/tests/data_api_test.py

typo fixes

---

docs/inference.md
pyproject.toml
src/qianfan/resources/llm/chat_completion.py

- **Description:** supported ai_pass chat models services
- **Issue:** #65 

feat: add apc aipass model supported

---

cookbook/agents/langchain_agent_with_qianfan_llm.ipynb

更新了天气 cookbook 中使用的 agent 语法，现在更加简洁，并且重新修正了排版

update: langchain_agent_with_qianfan_llm.ipynb using newest agent syntax

---

pyproject.toml

- **Description:** update version

feat: version->0.2.0

---

src/qianfan/extensions/langchain/agents/baidu_qianfan_endpoint.py

This PR introduces new langchain_core to fit newest langchain community trend #103 and helps to fix unreasonable diamond inheritance of qianfan langchain agents #102

introduce langchain_core

---

docs/configurable.md
src/qianfan/consts.py
src/qianfan/resources/images/text2image.py
src/qianfan/resources/llm/base.py
src/qianfan/resources/llm/chat_completion.py
src/qianfan/resources/llm/completion.py
src/qianfan/resources/llm/embedding.py
src/qianfan/resources/llm/plugin.py
src/qianfan/tests/chat_completion_test.py
src/qianfan/tests/utils/mock_server.py

- **Description:** support request_id
- **Issue:** #91 

feat: add request_id

---

src/qianfan/dataset/dataset.py
src/qianfan/dataset/table.py
src/qianfan/tests/dataset/table_test.py

向 Table 和 Dataset 中添加 col_renames 函数，并且移除 map 的空返回限制

feat: add col_renames method

---

src/qianfan/dataset/data_source.py
src/qianfan/dataset/dataset.py
src/qianfan/extensions/langchain/agents/baidu_qianfan_endpoint.py
src/qianfan/tests/dataset/data_source_test.py

1. `load` 方法支持从 hugginface 的数据集对象读取
2. `FileDataSource` 支持从文件夹批量导入数据集

feat: Dataset v1.3

---

src/qianfan/resources/llm/chat_completion.py
src/qianfan/resources/llm/completion.py

- **Description:** support `max_output_token` in eb & eb4 suppress field warning.
- **Issue:** #113 

feat: add  supported

---

docs/dataset.md
src/qianfan/tests/dataset/data_source_test.py

- **Description:** 在 Readme 中添加了有关文件夹导入和 HuggingFace 数据集的导入工作, 
- **Issue:** #113 ,

add dataset feature introduction in Dataset Readme

---

cookbook/finetune/trainer-finetune.ipynb

- **Description:** add `qianfan` installation cmd for cookbook
- **Tag maintainer:**  @stonekim

fix: add cookbook qianfan install command

---

src/qianfan/dataset/dataset.py
src/qianfan/resources/console/consts.py
src/qianfan/tests/trainer_test.py
src/qianfan/tests/utils/mock_server.py
src/qianfan/trainer/model.py

Replace this entire comment with:
- **Description:** Model 增加 `batch_run_on_qianfan` 函数, 

feat: add batch_run_on_qianfan on Model

---

src/qianfan/resources/llm/chat_completion.py
src/qianfan/resources/llm/completion.py

- **Description:** add chat law preset model service and params
- **Issue:** #124 

feat: support chat law

---

cookbook/dataset/how_to_use_qianfan_operator.ipynb
cookbook/finetune/api_based_finetune.ipynb
src/qianfan/config.py
src/qianfan/consts.py
src/qianfan/dataset/data_operator.py
src/qianfan/dataset/data_source.py
src/qianfan/dataset/dataset.py
src/qianfan/resources/console/consts.py
src/qianfan/resources/console/utils.py
src/qianfan/resources/requestor/console_requestor.py
src/qianfan/resources/tools/utils.py
src/qianfan/tests/dataset/data_source_test.py
src/qianfan/utils/bos_uploader.py

- **Description:** add how_to_use_qianfan_operator.ipynb and bugfix of dataset , 
- **Issue:** 
- #129 
- #130
-  #131
-  #132 
- **Tag maintainer:** @stonekim, @danielhjz, @ZingLix

add how_to_use_qianfan_operator.ipynb

---

src/qianfan/components/tool/base_tool.py
src/qianfan/components/tool/duckduckgo_search_tool.py
src/qianfan/components/tool/wikipedia_tool.py
src/qianfan/tests/tool_test.py
src/qianfan/utils/utils.py

- add base tool framework
- add duckduckgo_search and wikipedia tools.
- **Issue:** 
- #124
- **Dependencies:** duckduckgo_search (optional), wikipedia (optional)

feat: base tool framework

---

src/qianfan/components/tool/base_tool.py
src/qianfan/tests/tool_test.py
src/qianfan/utils/utils.py

- Add support for tool conversion from langchain.
- **Issue:** 
- #137
- **Dependencies:** langchain

feat: tool conversion from langchain

---

pyproject.toml
src/qianfan/resources/requestor/base.py
src/qianfan/resources/typing.py
src/qianfan/tests/latency_test.py

- add latency statistics
- update 0.2.3->0.2.4
- **Issue:** #137 
- **Tag maintainer:** @stonekim @ZingLix  @Dobiichi-Origami

feat[requestor]: add latency statistic

---

src/qianfan/resources/llm/chat_completion.py
src/qianfan/resources/llm/completion.py

- support model`Yi-34B-Chat`
- add `tools`, `tool_choice` for ERNIE-Bot-turbo
- add `tool_choice` for ERNIE-Bot
- **Issue:** #137 
- **Tag maintainer:** @stonekim,  @ZingLix @Dobiichi-Origami.

feat: support yi-34b-chat

---

src/qianfan/resources/auth/iam.py
src/qianfan/resources/console/utils.py

- **Description:** fix async console iam sign
- **Tag maintainer:** for a quicker response, please @-mention one of @stonekim, @ZingLix @Dobiichi-Origami.

fix: console async requestor & iamsign

---

cookbook/eb_search.ipynb

- **Description:** add resource calling baidu_search in `ERNIE-Bot-turbo`

feat: support baidu_search tool in ebturbo

---

src/qianfan/resources/images/text2image.py
src/qianfan/resources/llm/chat_completion.py
src/qianfan/resources/llm/completion.py
src/qianfan/resources/llm/embedding.py

- support `tao-8k`
- support `ERNIE-Bot-turbo-pro`
- support more params in `Stable-Diffusion-XL`
- **Issue:** #147 

chore: update preset models

---

src/qianfan/resources/llm/plugin.py

- **Description:** fix qianfan plugin
- **Tag maintainer:** @-mention one of @stonekim, @ZingLix @Dobiichi-Origami.

fix: plugin

---

src/qianfan/trainer/base.py
src/qianfan/trainer/event.py
src/scripts/run_test.sh

- fix event action_class and action_id
- **Tag maintainer:** @ZingLix

fix: event action class & action id

---

src/qianfan/consts.py
src/qianfan/resources/console/consts.py
src/qianfan/resources/console/service.py
src/qianfan/tests/service_test.py
src/qianfan/tests/utils/mock_server.py

- **Description:** resource service list
- **Issue:** #161 

feat: support service list

---

src/qianfan/common/tool/base_tool.py
src/qianfan/tests/tool_test.py

- Add support for tool conversion to langchain.
- **Issue:** 
- #161
- **Dependencies:** langchain

feat: tool conversion to langchain

---

pyproject.toml
src/qianfan/config.py
src/qianfan/consts.py
src/qianfan/resources/console/utils.py
src/qianfan/resources/llm/base.py
src/qianfan/resources/requestor/base.py
src/qianfan/resources/requestor/openapi_requestor.py
src/qianfan/resources/typing.py
src/qianfan/tests/retry_test.py
src/qianfan/tests/utils/mock_server.py

- **Description:** refactor retry:
- support jitter
- support retry_err_code custom.
- use tenacity for retrying
- **Issue:** #161 

feat: support tenacity retry

---

src/qianfan/resources/llm/chat_completion.py
src/qianfan/resources/llm/completion.py

- **Description:** rename model

feat: rename model：from ERNIE-Bot-turbo-pro to ERNIE-Speed

---

pyproject.toml
src/qianfan/resources/llm/chat_completion.py
src/qianfan/resources/llm/completion.py

- **Description:** update version & tool support open sources models
- **Issue:** #161 

chore: update version & resource

---

README.md
README.pypi.md
pyproject.toml
src/qianfan/extensions/langchain/agents/baidu_qianfan_endpoint.py

- **Description:** 添加反馈的badge
- **Issue:** None
- **Dependencies:** None
- **Tag maintainer:** @stonekim, @danielhjz, @ZingLix @Dobiichi-Origami

readme: add feedback badge

---

src/qianfan/common/client/main.py

- **Description:** 修复client中输入的中文不能被正确删除
- **Issue:** /

fix: chinese character cannot be deleted properly

---

docs/cli.md
src/qianfan/common/client/dataset.py

- **Description:** 数据集预览默认仅打印前5条，可以通过 `--row all` 打印所有数据
- **Issue:** /
- **Tag maintainer:** @stonekim, @danielhjz @Dobiichi-Origami.

feat: add dataset view default limit

---

docs/cli.md
src/qianfan/common/client/main.py

- **Description:** client异常默认不打印 traceback，可通过参数打开。用户未提供ak/sk时提示用户输入。
- **Issue:** /
- **Tag maintainer:**  @stonekim, @danielhjz, @Dobiichi-Origami

feat: optimize client traceback and input ak/sk

---

docs/cli.md
src/qianfan/common/client/completion.py
src/qianfan/common/client/dataset.py
src/qianfan/common/client/main.py

- **Description:** 优化 client 的帮助信息
- **Issue:** /

fix: update client help message

---

cookbook/function_call.ipynb

- **Description:**  add a function call cookbook for beginners.
- **Issue:** #177 

add function_call cookbook

---

cookbook/function_call.ipynb
cookbook/function_call_with_tool.ipynb

- **Description:** add call_function_with_tool.ipynb and fix call_funcion.ipynb, 
- **Issue:** #195,

add call_function_with_tool

---

README.md

- **Description:** readme增加client相关介绍
- **Issue:** /

readme: Add introduction for client

---

src/qianfan/resources/tools/tokenizer.py
src/qianfan/tests/utils/mock_server.py

- **Description:** 适配 tokenizer api 变动
- **Issue:** #195 

fix: tokenizer api change

---

src/qianfan/trainer/configs.py

- **Description:** fix short_name
- **Issue:** #195 

fix: trainer short name

---

docs/inference.md

- **Description:** fix plugins

fix: plugins docs

---

cookbook/finetune/api_based_finetune.ipynb
docs/train.md
src/qianfan/resources/console/finetune.py
src/qianfan/tests/finetune_test.py
src/qianfan/trainer/actions.py

- **Description:** 创建训练任务时要求传入 train_type

fix: require traintype when creating sft task

---

src/qianfan/common/hub/hub.py
src/qianfan/common/prompt/prompt.py
src/qianfan/config.py
src/qianfan/consts.py
src/qianfan/dataset/data_source.py
src/qianfan/trainer/configs.py

- **Description:** 增加sdk内读取文件编码的配置
- **Issue:** /

feat: add encoding config

---

src/qianfan/config.py
src/qianfan/consts.py
src/qianfan/resources/http_client.py

feat: add proxy support

---

src/qianfan/common/client/chat.py
src/qianfan/resources/llm/chat_completion.py
src/qianfan/resources/llm/completion.py

- **Description:** 修复 EB Speed 的链接
- **Issue:** #217

fix: update eb speed endpoint

---

cookbook/finetune/trainer_finetune.ipynb
pyproject.toml
src/qianfan/common/client/trainer.py
src/qianfan/tests/utils/mock_server.py
src/qianfan/trainer/actions.py
src/qianfan/trainer/configs.py
src/qianfan/trainer/finetune.py
src/qianfan/utils/bos_uploader.py
src/scripts/run_test.sh

- fix trainer with str id
- support field checking during trainer run
- support bos dataset

fix: trainer with str id

---

src/scripts/release_github.sh

- **Description:** fix release scripts

fix: release script

---

src/qianfan/resources/llm/plugin.py
src/qianfan/tests/plugin_test.py

This is just to correct typos mentioned in report issue: https://github.com/baidubce/bce-qianfan-sdk/issues/228

resolves baidubce/bce-qianfan-sdk#228

---

src/qianfan/resources/llm/plugin.py
src/qianfan/resources/requestor/base.py
src/qianfan/tests/plugin_test.py
src/qianfan/tests/trainer_test.py
src/qianfan/tests/utils/mock_server.py
src/qianfan/trainer/actions.py
src/qianfan/trainer/configs.py

- fix plugin response `_event`
- fix trainer validate fileds

fix: plugins & trainer validator

---

src/qianfan/common/prompt/prompt.py
src/qianfan/tests/prompt_class_test.py

- **Description:** 渲染 negative prompt 支持非字符串
- **Issue:** #235

fix: render negative prompt with non-str variable

---

docs/semantic_kernel.md

- **Description:** add sk docs
- **Tag maintainer:**

chore-sk-doc

---

src/qianfan/resources/requestor/base.py
src/qianfan/resources/requestor/openapi_requestor.py
src/qianfan/tests/retry_test.py

- **Description:** 流式请求不自动刷新 access token
- **Issue:** #235 

fix: access token not refreshed when using stream

---

python/qianfan/resources/llm/base.py

- **Description:** 修复了线程批量请求的竞争问题 

bug: fix thread work pool concurrent bug

---

.github/workflows/doc_build.yml
.github/workflows/go_ci.yml
.github/workflows/py_ci.yml

- **Description:** macos 上关闭 ntp，避免ut中时间检测出现问题
- **Issue:** /

action: disable ntp on macos

---

.github/labeler.yml
.github/workflows/auto_labeler.yml

- **Description:** PR 自动标签
- **Issue:** /

action: add auto labeler on pr

---

README.md

- **Description:** readme 增加 go 的 badge
- **Issue:** /

readme: add go badge

---

python/qianfan/dataset/dataset.py
python/qianfan/evaluation/evaluation_manager.py

- **Description:** 去掉了在线评估、在线推理、在线数据清洗部分对千帆数据源的限制要求, 

feat: 千帆数据集兼容性变更

---

python/pyproject.toml

- **Description:** dotenv 1.0 is not supported with python3.7
- **Issue:** #270 
- **Dependencies:** `dotenv`
- **Tag maintainer:** @stonekim @ZingLix  @Dobiichi-Origami

fix: compatiable with dotenv 1.0

---

python/qianfan/resources/llm/base.py

- **Description:** 降低了最大可并发的请求线程数到 1000
- **Issue:** #274 

fix: change MAX_WORKER_THREAD_COUNT to 1000

---

docs/cli.md
python/qianfan/common/client/plugin.py

- **Description:** client 支持调用一言插件
- **Issue:** #267 

feat: support eb plugin in client

---

cookbook/finetune/finetune_with_bos_and_evaluate.ipynb

- **Description:** fix a bug in cookbook finetune_with_bos_and_evaluate.ipynb and tag it for CI-testing, 
- **Issue:** ,

fix and tag ckbk finetune_with_bos_and_evaluate

---

.github/workflows/js_ci.yml
.github/workflows/js_release.yml

- **Description:** 增加 JS release note 的 action
- **Issue:** /

add js release action

---

python/qianfan/consts.py

- **Description:** 增加重试的错误码
- **Issue:** #283 

fix: add err code for retry

---

javascript/README.md
javascript/package.json
javascript/src/ChatCompletion/index.ts
javascript/src/Completions/index.ts
javascript/src/Embedding/index.ts
javascript/src/index.ts
javascript/src/test/chatCompletion.ts
javascript/src/test/completiont.ts
javascript/src/test/embedding.ts
javascript/src/utils.ts

- **Description:** JS SDK支持环境变量读取、修改及手动传入ak/sk
- **Tag maintainer:**@stonekim, @danielhjz, @ZingLix @Dobiichi, @Leophen

JS SDK支持环境变量读取、修改及手动传入ak/sk

---

python/qianfan/resources/rate_limiter.py
python/qianfan/resources/token_limiter.py

- **Description:** 修复了在 python 3.9 及以下版本中进行评估会报错的问题, 
- **Issue:** #289 ,

bugfix: Rpm bug fix

---

docs/go/config.md
docs/go/inference.md
docs/template/root_doc.rst_t
go/README.md
go/examples/README.md
go/examples/embedding_distance/main.go
go/examples/function_call/main.go
go/examples/list_model/main.go
go/examples/stream_chat/main.go
python/scripts/build_doc.sh

- **Description:** 增加 go 文档和 function call 示例
- **Issue:** /

doc: add go examples & docs

---

cookbook/plugin.ipynb

- **Description:** add cookbook plugin.ipynb, 
- **Issue:** #283 ,
- **Dependencies:**,

cookbook pluginV2

---

python/pyproject.toml
python/qianfan/resources/llm/base.py
python/qianfan/resources/llm/chat_completion.py
python/qianfan/resources/requestor/base.py
python/qianfan/resources/token_limiter.py
python/qianfan/resources/tools/tokenizer.py
python/qianfan/resources/typing.py
python/qianfan/tests/chat_completion_test.py
python/qianfan/tests/tokenizer_test.py
python/qianfan/tests/utils/mock_server.py

- **Description:** chat支持遗忘过长的消息
- **Issue:** #283 

feat: support forget old message in chat

---

cookbook/eb_search.ipynb
python/pyproject.toml
python/qianfan/dataset/data_source/file.py
python/qianfan/resources/llm/chat_completion.py
python/qianfan/resources/llm/completion.py

- Description:
- fix eb_search notebook
- support eb speed 128k
- Tag maintainer: f@stonekim, @danielhjz, @ZingLix @Dobiichi-Origami.

feat: support ebspeed128k & fix notebook

---

.gitignore
java/pom.xml

- **Description:** Update Java pom.xml

chore: update pom config

---

python/qianfan/dataset/consts.py
python/qianfan/dataset/data_source/base.py
python/qianfan/dataset/data_source/chunk_reader.py
python/qianfan/dataset/data_source/file.py
python/qianfan/dataset/data_source/utils.py
python/qianfan/dataset/dataset.py
python/qianfan/dataset/table.py
python/qianfan/dataset/table_utils.py
python/qianfan/tests/dataset/data_source_test.py
python/qianfan/tests/dataset/table_test.py

- **Description:** 针对 `Dataset` 所提供的操作函数支持了盘上处理的功能, 
- **Issue:** #303 ,

feat: Dataset manipulator update

---

cookbook/README.md
cookbook/batch_prediction.ipynb
cookbook/dataset/batch_inference_using_dataset.ipynb
cookbook/offline_batch_inference.ipynb
docs/batch_inference.md

- **Description:** cookbook 链接错误
- **Issue:** /

fix: cookbook link broken

---

javascript/src/Images/image2text.ts
javascript/src/Images/index.ts
javascript/src/Plugin/index.ts
javascript/src/Plugin/utilts.ts
javascript/src/index.ts
javascript/src/interface.ts
javascript/src/streaming/index.ts
javascript/src/test/image2text.ts
javascript/src/test/plugins.ts

- **Description:** a description of the change, 
- **Issue:** #326 ,
- **Tag maintainer:** @stonekim, @danielhjz, @ZingLix @Dobiichi-Origami, @dl102306 @Leophen .

AIPD-DEV-21689 [TechFeature] 一言插件 & 图生文

---

python/qianfan/dataset/data_source/file.py

- **Description:**  修复了导出到 jsonline 格式时会出现的格式错误问题, 
- **Issue:** #332 ,

bug: jsonline format issue fix

---

python/qianfan/dataset/dataset.py
python/qianfan/tests/trainer_test.py

- **Description:** 添加了一个参数用于控制 Dataset 批量推理输出结果的内容和存放介质
- **Issue:** #337 ,

bugfix: add output_prettified parameter

---

python/qianfan/dataset/data_source/baidu_qianfan.py
python/qianfan/dataset/data_source/bos.py
python/qianfan/dataset/data_source/file.py

- **Description:** 支持用户在向 BOS 或平台上传半处理的数据集时，自动（平台）或可选（BOS）的将数据集转换成千帆的格式 
- **Issue:** the issue #335 ,

feat: convert List[Dict] to List[List[Dict]] automatically

---

python/qianfan/tests/utils/mock_server.py

- **Description:** mockserver 遇到空body时报错
- **Issue:** /
- **Tag maintainer:** @danielhjz

fix: mock server not working when body is empty

---

javascript/package.json

- **Description:** 更新版本号 
- **Issue:** #326 ,
- **Tag maintainer:** @Leophen, @stonekim, @danielhjz, @ZingLix @Dobiichi-Origami.

fix: 更新版本号

---

python/pyproject.toml
python/qianfan/common/client/trainer.py
python/qianfan/trainer/configs.py

- 优化trainer model list展示归类
- fix lint warning
- **Issue:** #324 
- **Tag maintainer:** @ZingLix @stonekim

feat: add model_type & fix pyproject setting

---

python/scripts/run_test_ntbk.sh
python/test_CI/conftest.py
python/test_CI/utils/cookbook_operate.py

- **Description:** fix ckbk test about dir path, 
- **Issue:**  ,
- **Dependencies:**  ,

fix ckbk test

---

java/src/main/java/com/baidubce/qianfan/QianfanClient.java
java/src/main/java/com/baidubce/qianfan/core/QianfanConfig.java
java/src/main/java/com/baidubce/qianfan/core/auth/Auth.java
java/src/main/java/com/baidubce/qianfan/core/auth/IAMAuth.java
java/src/main/java/com/baidubce/qianfan/core/auth/QianfanOAuth.java
java/src/main/java/com/baidubce/qianfan/model/constant/ModelEndpoint.java
java/src/main/java/com/baidubce/qianfan/util/EnvParser.java

- **Description:** add dot env config file support for java sdk
- **Issue:** #325

feat: add dot env config file support

---

go/qianfan/base_model.go
go/qianfan/version.go

- **Description:** 修复流式场景下不报错的问题
- **Issue:** /

fix[go]: error not reported when using stream

---

python/qianfan/dataset/dataset.py
python/qianfan/resources/rate_limiter.py
python/qianfan/resources/token_limiter.py
python/qianfan/tests/dataset/data_source_test.py
python/qianfan/tests/rate_limiter_test.py
python/qianfan/tests/token_limiter_test.py

- **Description:** 从过去三个星期发现的 Bug 中总结并增加了 15 个新单测来扩大单测覆盖面，减少 Bug 出现的概率。

fix: Dataset/RateLimiter bugs，add more unit tests

---

cookbook/evaluation/local_eval_with_qianfan.ipynb
python/qianfan/evaluation/local_evaluator.py

- **Description:** hotfix for local_evaluator import error, 
- **Issue:** #348 

fix local_evaluator import error

---

python/qianfan/consts.py
python/qianfan/resources/console/consts.py
python/qianfan/resources/console/model.py

- **Description:** fix type check, add 2 function to adapt api, 
- **Issue:** ,

fix[resource]: model apis

---

python/qianfan/common/client/trainer.py
python/qianfan/common/client/utils.py

- **Description:** 调整 deprecated 打印的顺序
- **Issue:** #345 

optimize: adjust deprecated item location in cli

---

java/README.md
java/example/pom.xml
java/example/src/main/java/com/baidubce/Text2ImageExample.java

- **Description:** add java text to image example
- **Issue:** #325 

feat: add java text to image example

---

python/pyproject.toml

fix[python]: fix version

---

cookbook/README.md

- **Description:** fix cookbook readme.md
- **Issue:** 

fix[cookbook]: fix README.md

---

python/qianfan/extensions/langchain/agents/baidu_qianfan_endpoint.py

- **Description:** 修复了 langchain function call 失效的问题, 

fix: replace additional_kwargs to response_metadata

---

javascript/package.json
javascript/src/Limiter/RateLimiter/index.ts
javascript/src/Limiter/TokenLimiter/__tests__/index.test.ts
javascript/src/Limiter/TokenLimiter/index.ts
javascript/yarn.lock

- **Description:** 限流依赖库变更, 
- **Issue:** the issue #382  ,
- **Tag maintainer:** @dl102306 , @Leophen ,@stonekim, @danielhjz, @ZingLix @Dobiichi-Origami.

fix:【js】限流依赖库变更

---

python/qianfan/extensions/openai/adapter.py

- **Description:** OpenAI 适配器转换 function_call 错误
- **Issue:** /

fix: openai adapter cannot convert tool_choice from function_call

---

cookbook/finetune/text2image_finetune.ipynb

- **Description:** text2image finetune cookbook
- **Issue:** #367 
- **Tag maintainer:** @stonekim  @Dobiichi-Origami @ZingLix

feat[coobkook]: add text2image cookbooks

---

java/src/main/java/com/baidubce/qianfan/Qianfan.java
java/src/main/java/com/baidubce/qianfan/QianfanClient.java
java/src/main/java/com/baidubce/qianfan/core/QianfanConfig.java
java/src/main/java/com/baidubce/qianfan/model/BaseRequest.java
java/src/main/java/com/baidubce/qianfan/model/RetryConfig.java
java/src/main/java/com/baidubce/qianfan/model/constant/APIErrorCode.java
java/src/main/java/com/baidubce/qianfan/model/exception/ApiException.java
java/src/main/java/com/baidubce/qianfan/util/function/ThrowingFunction.java
java/src/main/java/com/baidubce/qianfan/util/function/ThrowingSupplier.java
java/src/main/java/com/baidubce/qianfan/util/http/ContentType.java
java/src/main/java/com/baidubce/qianfan/util/http/HttpClient.java
java/src/main/java/com/baidubce/qianfan/util/http/HttpStatus.java

Replace this entire comment with:
- **Description:** add support for request retries, 
- **Issue:** 
- **Dependencies:** none,

feat: add support for request retries

---

java/pom.xml
java/src/main/java/com/baidubce/qianfan/Qianfan.java
java/src/main/java/com/baidubce/qianfan/QianfanClient.java
java/src/main/java/com/baidubce/qianfan/core/QianfanConfig.java
java/src/main/java/com/baidubce/qianfan/core/RateLimiter.java
java/src/main/java/com/baidubce/qianfan/model/RateLimitConfig.java
java/src/main/java/com/baidubce/qianfan/util/TokenBucketLimiter.java

Replace this entire comment with:
- **Description:** add support for rate limit
- **Issue:** 

feat: add support for rate limit

---

java/src/main/java/com/baidubce/qianfan/QianfanClient.java

- **Description:** fix max wait interval in back off retry
- **Issue:** 

fix: max wait interval in back off retry

---

python/qianfan/dataset/dataset.py
python/qianfan/evaluation/evaluation_manager.py

- **Description:** 修复了千帆评估数据集导出格式的变更所导致的问题, 

fix: fix format issue

---

java/example/pom.xml
java/example/src/main/java/com/baidubce/RateLimitConfigExample.java
java/example/src/main/java/com/baidubce/RetryConfigExample.java

- **Description:** add retry and ratelimit example, 
- **Issue:** none,
- **Dependencies:** none,
- **Tag maintainer:** for a quicker response, @stonekim, @danielhjz, @ZingLix @Azure99

feat: add retry and rate limit example in java

---

java/pom.xml
java/src/main/java/com/baidubce/qianfan/QianfanClient.java

- **Description:** bump version to 0.0.4

chore: bump version to 0.0.4

---

python/qianfan/errors.py
python/qianfan/resources/auth/oauth.py

- **Description:** 完善 OpenAPI 鉴权失败时报错信息
- **Issue:** /

fix: update error msg when oauth failed

---

python/scripts/release_note.sh

- **Description:** hotfix for release_note.sh , 
- **Issue:** #422 ,

fix: hotfix for release_note.sh

---

.github/workflows/java_ci.yml

- **Description:** java build pipeline

chore: java build pipeline

---

java/README.md
java/example/pom.xml

- **Description:** update sdk version to 0.0.4

docs: update sdk version to 0.0.4

---

java/src/main/java/com/baidubce/qianfan/core/QianfanConfig.java

- **Description:** increase access token refresh interval to 3600

fix: increase access token refresh interval to 3600

---

.github/workflows/js_release.yml
README.md
javascript/src/Base/index.ts
javascript/src/DynamicModelEndpoint/index.ts

- **Description:** 文档更新
- **Issue:** # 428,
- **Tag maintainer:** @Leophen , @-mention one of @stonekim, @danielhjz, @ZingLix @Dobiichi-Origami.

fix: update readme

---

.github/workflows/js_release.yml
README.md
javascript/package.json
javascript/src/Base/index.ts
javascript/src/ChatCompletion/__tests__/index.test.ts
javascript/src/Completions/__tests__/index.test.ts
javascript/src/DynamicModelEndpoint/__tests__/index.test.ts
javascript/src/DynamicModelEndpoint/index.ts
javascript/src/DynamicModelEndpoint/utils.ts
javascript/src/Embedding/__tests__/index.test.ts
javascript/src/Fetch/fetch.ts
javascript/src/Images/__tests__/index.test.ts
javascript/src/Plugin/__tests__/index.test.ts
javascript/src/Plugin/index.ts
javascript/src/utils.ts

- **Description:** 低版本node, ReadableStream不兼容, 
- **Issue:** #442 ,
- **Tag maintainer:** @dl102306, @Leophen ,@stonekim, @danielhjz, @ZingLix @Dobiichi-Origami.

bug: 低版本node, ReadableStream不兼容

---

python/qianfan/autotuner/runner/qianfan_runner.py

- **Description:** 自动推荐参数使用evaluator进行综合指标计算
- **Issue:** /

feat: autotuner support evaluator summarize

---

.github/workflows/go_release.yml

- **Description:** hotfix for go release note CI 
- **Issue:** ,

fix[go]: fix go release note CI

---

python/pyproject.toml
python/qianfan/trainer/finetune.py

- support `trainer.show()`
- fix `trainer.output` error when unfinished task
- **Tag maintainer:**  @stonekim, @ZingLix @Dobiichi-Origami.

fix[trainer]: fix output & support trainer.show

---

python/qianfan/dataset/data_source/chunk_reader.py
python/qianfan/dataset/dataset.py
python/qianfan/dataset/table.py
python/qianfan/evaluation/evaluation_manager.py

- **Description:** 增加了 sample 函数

feat: add sample function

---

python/qianfan/dataset/data_source/chunk_reader.py
python/qianfan/dataset/dataset.py
python/qianfan/dataset/table.py
python/qianfan/evaluation/evaluation_manager.py

- **Description:** add shuffle func,

add shuffle func

---

python/pyproject.toml
python/qianfan/dataset/data_source/chunk_reader.py
python/qianfan/dataset/dataset.py
python/qianfan/dataset/table.py
python/qianfan/evaluation/evaluation_manager.py
python/qianfan/resources/requestor/openapi_requestor.py
python/qianfan/trainer/finetune.py

- **Description:** 把 `add_default_group_column` 添加进 `pack` 函数中, 

把 `add_default_group_column` 添加进 `pack` 函数中

---

python/qianfan/common/client/openai_adapter.py

- **Description:** openai server 流式缺少 [DONE] 标记
- **Issue:** /

fix: openai server response does not have done flag

---

dotenv_config_sample.env
python/qianfan/consts.py

- **Description:** 推理默认超时时间改为 300s
- **Issue:** #458 

update default retry timeout

---

python/qianfan/dataset/data_source/file.py

- **Description:** 增加了对 dpo 数据集导出格式的适配,

feat: remove none from json output

---

python/pyproject.toml
python/qianfan/resources/__init__.py
python/qianfan/resources/llm/rerank.py

- 支持reranker模型调用
- **Issue:** #458 

feat[resource]: support reranker

---

go/qianfan/auth.go
go/qianfan/auth_test.go
go/qianfan/base_model.go
go/qianfan/chat_completion.go
go/qianfan/chat_completion_test.go
go/qianfan/completion.go
go/qianfan/completion_test.go
go/qianfan/config.go
go/qianfan/console_base.go
go/qianfan/consts.go
go/qianfan/embdding.go
go/qianfan/embedding_test.go
go/qianfan/error.go
go/qianfan/model_endpoint_retriever.go
go/qianfan/requestor.go
go/qianfan/service.go
go/qianfan/service_test.go
python/qianfan/tests/utils/mock_server.py

- **Description:** 支持动态获取模型 endpoing
- **Issue:** /

feat[go]: support retrieve model endpoint dynamically

---

go/qianfan/auth.go
go/qianfan/auth_test.go
go/qianfan/base_model.go
go/qianfan/chat_completion.go
go/qianfan/completion.go
go/qianfan/console_base.go
go/qianfan/embdding.go
go/qianfan/model_endpoint_retriever.go
go/qianfan/options.go
go/qianfan/requestor.go
go/qianfan/service.go
go/qianfan/utils.go

- **Description:** 支持 context
- **Issue:** #464 

feat[go]: support context

---

.github/workflows/go_release.yml

- **Description:**  fix release_note.sh for go, 
- **Issue:** ,
- **Tag maintainer:** @-mention one of @stonekim, @danielhjz, @ZingLix @Dobiichi-Origami.

fix[workflow]: fix release_note.sh

---

python/qianfan/common/client/openai_adapter.py

- **Description:** Windows 上 qianfan openai -d 无法正常工作
- **Issue:** #476 

fix: openai adapter detached mode not working on windows

---

python/pyproject.toml
python/qianfan/dataset/data_source/chunk_reader.py
python/qianfan/dataset/data_source/file.py
python/qianfan/dataset/data_source/utils.py
python/qianfan/dataset/dataset.py
python/qianfan/tests/dataset/data_source_test.py

- **Description:** 增加了针对多进程并行读一个数据集的文件锁，以及移除了对 `clevercsv` 的依赖
- **Dependencies:** `filelock`

feat: Dataset create file lock

---

python/qianfan/consts.py
python/qianfan/resources/auth/oauth.py
python/qianfan/resources/console/utils.py
python/qianfan/resources/requestor/base.py
python/qianfan/resources/requestor/openapi_requestor.py

- **Description:** 增加提示可能错误原因的功能
- **Issue:** #498 

feat: add possible error reason

---

README.md
docs/dataset.md
docs/install.md
python/Makefile
python/pyproject.toml
python/qianfan/dataset/data_source/baidu_qianfan.py
python/qianfan/dataset/data_source/bos.py
python/qianfan/dataset/data_source/file.py
python/qianfan/dataset/dataset.py
python/qianfan/utils/fake_pyarrow/__init__.py

update markdown file

---

cookbook/batch_prediction.ipynb
docs/batch_inference.md
docs/inference.md

- **Description:** 批量推理文档错误修正
- **Issue:** #503 

doc: fix error in batch inference

---

python/qianfan/utils/bos_uploader.py

- **Description:** 修复可能的 redos 
- **Issue:** #445 

fix: Redos Vulnerability

---

python/qianfan/resources/llm/base.py
python/qianfan/resources/llm/chat_completion.py
python/qianfan/resources/requestor/base.py
python/qianfan/resources/requestor/openapi_requestor.py
python/qianfan/resources/typing.py

- **Description:**  QfMessages 添加超参字段，支持在批量请求的场景下为每条请求分别指定超参, 并且提升了延迟检测的精度

feat: 支持批量请求时在单条信息中附带超参信息

---

README.md
docs/model.md
python/qianfan/model/model.py
python/qianfan/resources/llm/base.py
python/qianfan/resources/llm/chat_completion.py

- **Description:** update model markdown docs
- **Tag maintainer:**  @stonekim , @ZingLix @Dobiichi-Origami.

fix: model md

---

cookbook/function_call.ipynb
docs/inference.md
python/qianfan/__init__.py
python/qianfan/resources/__init__.py
python/qianfan/resources/llm/function.py
python/qianfan/resources/llm/functions.py
python/qianfan/tests/chat_completion_test.py
python/qianfan/tests/utils/mock_server.py

- **Description:** support `ernie-function` calling
- **Issue:** 
- **Tag maintainer:**

feat[resource]: add `Function` for function calling

---

python/pyproject.toml

- **Description:** update version->0.3.11
- **Issue:** #498 

Update pyproject.toml version

---

java/src/main/java/com/baidubce/qianfan/Qianfan.java
java/src/main/java/com/baidubce/qianfan/QianfanClient.java
java/src/main/java/com/baidubce/qianfan/model/BaseResponse.java

- **Description:** add raw http response headers
- **Issue:** #506 

feat: raw http response headers

---

java/src/main/java/com/baidubce/qianfan/model/chat/ChatResponse.java

- **Description:** fix incorrect description of flag field
- **Issue:** #508 

fix: incorrect description of flag field

---

java/pom.xml
java/src/main/java/com/baidubce/qianfan/QianfanClient.java
java/src/main/java/com/baidubce/qianfan/core/ModelEndpointRetriever.java

- **Description:** bump version to 0.0.5 & update model endpoint list

chore: bump version to 0.0.5 & update model endpoint list

---

javascript/src/Base/index.ts
javascript/src/DynamicModelEndpoint/index.ts
javascript/src/Fetch/fetch.ts
javascript/src/utils.ts

- **Description:** 浏览器sdk, 
- **Issue:** the issue #524,

feat: 浏览器SDK

---

python/qianfan/consts.py
python/qianfan/dataset/dataset_utils.py
python/qianfan/resources/console/charge.py
python/qianfan/resources/console/data.py
python/qianfan/tests/data_api_test.py
python/qianfan/tests/rpm_and_tpm_test.py
python/qianfan/tests/utils/mock_server.py

- **Description:** 数据管控 API 更新，新增资源购买 API, 

feat: 数据管控 API 更新，新增资源购买 API

---

java/README.md
java/example/pom.xml

- **Description:** update version to 0.0.5 in docs & examples

docs: bump version to 0.0.5

---

python/qianfan/common/prompt/prompt.py
python/qianfan/resources/console/prompt.py

- **Description:** 更新 prompt 的 type hint
- **Issue:** #514 

update: prompt type hint

---

docs/use_guidance_with_qianfan.md
python/pyproject.toml
python/qianfan/extensions/guidance/__init__.py
python/qianfan/extensions/guidance/_qianfan.py

- **Description:** 在 Extension 中增加了 Guidance 的支持代码, 
- **Dependencies:** guidance,

feat: 添加 Guidance 支持

---

.github/workflows/js_release.yml

- **Description:** fix js release ci action
- **Tag maintainer:** @wangting829

fix js_release.yml

---

javascript/README.md
javascript/package.json
javascript/src/DynamicModelEndpoint/index.ts
javascript/src/DynamicModelEndpoint/utils.ts
javascript/src/Reranker/__tests__/index.test.ts
javascript/src/Reranker/index.ts
javascript/src/Reranker/utilts.ts
javascript/src/constant.ts
javascript/src/enum.ts
javascript/src/interface.ts
javascript/src/test/reranker.ts

- **Description:** JS Reranker, 
- **Issue:** the issue #538,
- **Tag maintainer:** @wangting829, @stonekim, @danielhjz, @ZingLix @Dobiichi-

JS Reranker

---

python/pyproject.toml
python/qianfan/tests/tool_test.py

- **Description:** 修复langchain升级导致的ci问题
- **Issue:** #536 

fix: langchain upgraded error

---

docs/batch_inference.md
python/qianfan/consts.py
python/qianfan/resources/console/data.py

- **Description:** 支持批量推理任务list
- **Issue:** #536 
- **Tag maintainer:**  @ZingLix @Dobiichi-Origami.

feat: support batch_inference task list

---

docs/trainer.md
python/pyproject.toml
python/qianfan/model/model.py
python/qianfan/tests/trainer_test.py
python/qianfan/trainer/actions.py
python/qianfan/trainer/configs.py
python/qianfan/trainer/post_pretrain.py

- **Description:** 支持DatasetConfig，支持通用语料混合训练
- **Issue:** #536 
- **Tag maintainer:**  @ZingLix @Dobiichi-Origami.

feat: support datasetconfig in trainer

---

javascript/package.json

- **Description:**update model list, 
- **Issue:** the issue #550  ,

update model list

---

python/pyproject.toml
python/qianfan/tests/trainer_test.py
python/qianfan/tests/utils/mock_server.py
python/qianfan/trainer/actions.py

- **Description:** 修复splitratio导致的trainer报错
- **Issue:**
- **Tag maintainer:** @stonekim, @ZingLix @Dobiichi-Origami.

fix: trainer run split_ratio

---

java/pom.xml
java/src/main/java/com/baidubce/qianfan/QianfanClient.java
java/src/main/java/com/baidubce/qianfan/core/ModelEndpointRetriever.java

- **Description:** bump version to 0.0.6 & update model endpoint list
- **Dependencies:** none,

chore: bump version to 0.0.6 & update model endpoint list

---

java/src/main/java/com/baidubce/qianfan/util/http/HttpClient.java

- **Description:** use system properties for proxy settings in HttpClient configuration
- **Issue:** #496 

feat: use system properties in http client configuration

---

javascript/package.json
javascript/rollup.config.mjs
javascript/src/Base/index.ts
javascript/src/DynamicModelEndpoint/__tests__/index.test.ts
javascript/src/DynamicModelEndpoint/index.ts
javascript/src/Fetch/browserFetch.ts
javascript/src/Fetch/index.ts
javascript/src/Fetch/nodeFetch.ts
javascript/src/HttpClient/auth.ts
javascript/src/HttpClient/index.ts
javascript/src/streaming/index.ts
javascript/src/utils.ts
javascript/yarn.lock

- **Description:** 浏览器sdk无需配置polyfill, 
- **Issue:** the issue #559,
- **Tag maintainer:** @dl102306,@stonekim, @danielhjz, @ZingLix @Dobiichi-Origami.

feat: 浏览器sdk解偶打包工具

---

javascript/package.json
javascript/rollup.config.mjs
javascript/src/Base/index.ts
javascript/src/DynamicModelEndpoint/__tests__/index.test.ts
javascript/src/DynamicModelEndpoint/index.ts
javascript/src/Fetch/browserFetch.ts
javascript/src/Fetch/index.ts
javascript/src/Fetch/nodeFetch.ts
javascript/src/HttpClient/auth.ts
javascript/src/HttpClient/index.ts
javascript/src/streaming/index.ts
javascript/src/utils.ts
javascript/yarn.lock

feat: 浏览器sdk解偶polyfill (#560)

---

javascript/src/utils.ts

js 添加浏览器埋点

---

java/README.md
java/example/pom.xml
java/example/src/main/java/com/baidubce/HttpProxyExample.java
java/example/src/main/java/com/baidubce/RerankExample.java

- **Description:** [a description of the change, ](docs: add reranker & proxy example)

docs: add reranker & proxy example

---

python/qianfan/common/client/main.py
python/qianfan/common/client/proxy.py

- **Description:** Proxy 服务支持设置证书 

feat: Proxy 服务支持设置证书

---

python/qianfan/resources/console/model.py
python/qianfan/trainer/actions.py
python/qianfan/trainer/finetune.py

- 修复trainer dpo增量训练被归到SFT训练任务的问题
- **Issue:** #556 

fix: dpo increment training

---

python/qianfan/dataset/dataset.py
python/qianfan/dataset/dataset_utils.py
python/qianfan/dataset/streamlit_script.py

- **Description:** 数据洞察使用 streamlit 进行页面重构, 

feat: 数据洞察使用 streamlit 进行页面重构

---

docs/configurable.md
dotenv_config_sample.env
python/pyproject.toml
python/qianfan/common/persister/persist.py
python/qianfan/config.py
python/qianfan/consts.py
python/qianfan/dataset/consts.py
python/qianfan/dataset/data_source/baidu_qianfan.py
python/qianfan/dataset/data_source/bos.py
python/qianfan/dataset/data_source/utils.py
python/qianfan/resources/console/model.py
python/qianfan/resources/llm/base.py
python/qianfan/trainer/actions.py
python/qianfan/trainer/dpo.py
python/qianfan/trainer/finetune.py
python/qianfan/trainer/pipeline.py
python/qianfan/trainer/post_pretrain.py
python/qianfan/utils/cache/__init__.py
python/qianfan/utils/cache/base.py

- **Description:** 支持自定义CacheDir
- **Issue:** 
- **Tag maintainer:** @stonekim, @ZingLix @Dobiichi-Origami.

feat: custom cache dir

---

python/qianfan/dataset/stress_test/load_runner.py
python/qianfan/dataset/stress_test/qianfan_llm_load.py
python/qianfan/dataset/stress_test/yame/distributor.py

- **Description:** 修复distributor中的assert错误 、压测返回非0时依然打印统计结果，以及对ChatCompletion中的错误进行捕获
- **Dependencies:** 无

修复distributor中的assert错误 & 压测返回非0时依然打印统计结果

---

python/qianfan/resources/requestor/base.py
python/qianfan/resources/requestor/openapi_requestor.py

- **Description:** 修复由于限流时间太长导致超过iam签名时长从而鉴权失败的问题
- **Issue:** /

fix: 修复由于限流导致iam签名过期

---

java/src/main/java/com/baidubce/qianfan/Qianfan.java
java/src/main/java/com/baidubce/qianfan/QianfanClient.java
java/src/main/java/com/baidubce/qianfan/core/ModelEndpointRetriever.java
java/src/main/java/com/baidubce/qianfan/core/builder/PluginBuilder.java
java/src/main/java/com/baidubce/qianfan/model/plugin/PluginHistory.java
java/src/main/java/com/baidubce/qianfan/model/plugin/PluginLLM.java
java/src/main/java/com/baidubce/qianfan/model/plugin/PluginMetaInfo.java
java/src/main/java/com/baidubce/qianfan/model/plugin/PluginRequest.java
java/src/main/java/com/baidubce/qianfan/model/plugin/PluginResponse.java
java/src/main/java/com/baidubce/qianfan/model/plugin/PluginUsage.java

- **Description:** add plugin support

feat: add plugin support

---

docs/use_guidance_with_qianfan.md

@stonekim, @danielhjz, @ZingLix @Dobiichi-Origami.

bugfix: 修复文档错误

---

python/qianfan/common/persister/persist.py
python/qianfan/config.py
python/qianfan/consts.py
python/qianfan/resources/llm/base.py
python/qianfan/utils/cache/base.py

- **Description:** 支持`QIANFAN_DISABLE_CACHE`按需去掉缓存配置
- **Issue:** 

feat: support disable cache

---

go/qianfan/version.go

- **Description:** update go versoin
- **Tag maintainer:**  @ZingLix @Dobiichi-Origami.

chore[go]: update version->0.0.7

---

python/qianfan/extensions/openai/adapter.py

- **Description:** 修复openai adapter接口没有finish_reason字段时报错
- **Issue:** #595 

fix: openai adapter 兼容未提供 finish_reason 的接口

---

python/qianfan/dataset/data_source/baidu_qianfan.py
python/qianfan/dataset/data_source/bos.py
python/qianfan/dataset/data_source/file.py
python/qianfan/dataset/data_source/utils.py
python/qianfan/dataset/table.py

@stonekim, @danielhjz, @ZingLix @Dobiichi-Origami

feat: Dataset 支持缓存关闭的情况下操作

---

go/qianfan/chat_completion.go
java/src/main/java/com/baidubce/qianfan/core/ModelEndpointRetriever.java
javascript/src/ChatCompletion/utils.ts
javascript/src/DynamicModelEndpoint/utils.ts
python/qianfan/resources/llm/chat_completion.py

@stonekim, @danielhjz, @ZingLix @Dobiichi-Origami.

feat: 添加三个新模型的信息到 Py & Go

---

docs/stress_test.md

- **Description:**  更新压测文档
- **Issue:** the issue # it fixes (if applicable),
- **Tag maintainer:** @stonekim, @ZingLix @Dobiichi-Origami.

Update stress_test.md with deps install

---

python/pyproject.toml
python/qianfan/resources/requestor/openapi_requestor.py

- **Description:** 私有化跳过现有 openapi 鉴权逻辑
- **Issue:**/

fix: 私有化鉴权逻辑修复

---

python/qianfan/dataset/dataset.py
python/qianfan/dataset/table.py

- **Description:** Table 对象现在正式支持 for 循环遍历，并且通过在压测中设置 `no_proxy="*"` 解决了 MacOS 下的 Fork 警告问题, 

feat: 为 `Table` 对象添加 `__iter__` 与 `__next__` 函数，在压测中自动设置 `no_proxy="*"`

---

cookbook/evaluation/opencompass_evaluator.ipynb
docs/evaluation.md

@stonekim, @danielhjz, @ZingLix @Dobiichi-Origami.

doc: 更新了 Evaluation 相关内容的文档

---

python/qianfan/consts.py

@stonekim, @danielhjz, @ZingLix @Dobiichi-Origami.

bugfix: 更新资源购买接口 Action

---

javascript/README.md
javascript/browser.md
javascript/package.json
javascript/src/DynamicModelEndpoint/utils.ts
javascript/src/utils.ts

- **Description:** 文档拆分&模型更新, 
- **Issue:** the issue #624 ,

feat: 文档拆分&更新模型

---

python/qianfan/resources/llm/base.py
python/qianfan/utils/utils.py

- **Description:** models() 支持作为 class method
- **Issue:** /

feat: models() 支持作为 class method

---

java/README.md
java/example/pom.xml
java/pom.xml
java/src/main/java/com/baidubce/qianfan/QianfanClient.java

- **Description:** chore: bump version to 0.0.9

chore: bump version to 0.0.9

---

python/qianfan/extensions/openai/adapter.py

- **Description:** `tool_choice` 值为 `auto` 时忽略，eb不支持 
- **Issue:** /

fix: openai adapter `tool_choice` 忽略 `auto`

---

python/qianfan/resources/llm/base.py

- **Description:** v2接口模型名全部小写
- **Issue:** /

fix: v2 模型自动小写

---

docs/trainer.md
python/Makefile
python/pyproject.toml
python/qianfan/common/client/openai_adapter.py
python/qianfan/resources/console/finetune.py
python/qianfan/tests/trainer_test.py
python/qianfan/trainer/actions.py
python/qianfan/trainer/configs.py
python/qianfan/trainer/finetune.py
python/qianfan/utils/utils.py

- **Description:** 支持一言混合语料
- **Issue:** the issue # it fixes (if applicable),

feat[trainer]: support yiyan corpus

---

docs/trainer.md

- **Description:** fix trainer docs
- **Issue:** 

fix[docs]: support yiyan corpus fix docs

---

python/qianfan/common/client/trainer.py
python/qianfan/trainer/actions.py
python/qianfan/trainer/configs.py
python/qianfan/trainer/finetune.py

- 支持传入model进行增量训练
- 新增`ResouceConfig`用于定义训练资源配置
- **Issue:** the issue # it fixes (if applicable),

feat[trainer]: support resource config and increment training from model

---

javascript/package.json
javascript/src/Base/index.ts

- Description: getAccessToken this 显式绑定问题,
- Issue: the issue https://github.com/baidubce/bce-qianfan-sdk/issues/655,
- Tag maintainer: @dl102306 @wangting829

fix: 修复 issues/655 this 显式绑定问题

---

.github/workflows/doc_build.yml
.github/workflows/doc_release.yml
python/pyproject.toml
python/qianfan/dataset/stress_test/load_runner.py

- **Description:** fix doc ci
- **Tag maintainer:**@ZingLix @Dobiichi-Origami.

fix: doc ci

---

python/qianfan/dataset/stress_test/yame/utils.py

- **Description:** 修复压测工具中启动进程时判断端口是否被占用可能不生效的问题
- **Dependencies:** None

修复压测工具中判断端口是否被占用时可能不生效的问题

---

python/qianfan/common/client/main.py
python/qianfan/common/client/proxy.py
python/qianfan/extensions/proxy/proxy.py

- **Description:** 新增access_token
- **Issue:** 

feat-pyproxyV2

---

python/qianfan/resources/requestor/openapi_requestor.py

- **Description:** 签名逻辑已迁移至 `_preprocess_request`，去除原有iam签名问题
- **Issue:** /

fix: 修复 iam 重复签名的问题

---

docs/stress_test.md
python/qianfan/dataset/stress_test/load_runner.py
python/qianfan/dataset/stress_test/load_statistics.py
python/qianfan/dataset/stress_test/qianfan_llm_load.py
python/qianfan/dataset/stress_test/yame/runner.py

- **Description:** 1. 修复了报告和cmd结果不一致的问题
2. 现在将报告分为多轮的文件夹分别展示
- **Issue:** 

feat-stress_test-fixed

---

go/qianfan/auth.go
go/qianfan/auth_test.go
go/qianfan/config.go
go/qianfan/requestor.go

feat[golang]: support golang access_token auth config

---

python/qianfan/common/client/openai_adapter.py
python/qianfan/extensions/openai/adapter.py

- **Description:** openai adapter支持额外参数
- **Issue:** /

feat: openai adapter支持额外参数

---

python/qianfan/resources/llm/function.py

- **Description:** `ERNIE-Functions-8K`支持流式请求

fix: functions stream

---

python/qianfan/resources/rate_limiter.py

重构了 `RateLimiter` 的实现以修复在特定场景下的问题

feat: `RateLimiter` 重构

---

python/qianfan/resources/rate_limiter.py
python/qianfan/tests/rate_limiter_test.py

fix: ratelimiter ut

---

go/qianfan/base_model.go
go/qianfan/config.go
go/qianfan/consts.go
go/qianfan/utils.go

- **Description:** 支持自定义重试错误码
- **Issue:** /

feat: 支持自定义重试错误码

---

javascript/src/DynamicModelEndpoint/utils.ts

- **Description:** ernie-lite-v, 
- **Issue:** the issue #716,

feat:【js】ernie-lite-v

---

docs/stress_test.md
python/qianfan/dataset/stress_test/qianfan_llm_load.py

- **Description:** fix bugs in qianfan_llm_load, including key error.
- **Issue:**

修复key error报错

---

python/qianfan/resources/requestor/openapi_requestor.py

- **Description:** 增加了检测字段完整性&补全字段的功能
- **Issue:** 
- **Tag maintainer:**@stonekim, @danielhjz, @ZingLix @Dobiichi-Origami.

修复了因为字段不完整导致无法正常使用多轮functioncall请求的问题

---

.github/workflows/js_release.yml
docs/javascript/Proxy.md
docs/javascript/console.md
docs/stress_test.md
go/qianfan/base_model.go
go/qianfan/config.go
go/qianfan/consts.go
go/qianfan/utils.go
javascript/package.json
javascript/src/DynamicModelEndpoint/utils.ts
javascript/src/Fetch/nodeFetch.ts
javascript/src/HttpClient/index.ts
javascript/src/index.ts
javascript/src/utils.ts
javascript/yarn.lock
python/qianfan/dataset/stress_test/qianfan_llm_load.py
python/qianfan/resources/console/consts.py
python/qianfan/resources/requestor/openapi_requestor.py
python/qianfan/trainer/actions.py
python/qianfan/trainer/configs.py

- **Description:** 支持afs训练
- **Tag maintainer:**  @ZingLix @Dobiichi-Origami.

feat: support trainer with AFS

---

go/examples/call_console/main.go

chore: add go call console action

---

go/qianfan/version.go

- **Description:** release go sdk v0.0.11
- **Issue:** /

release: go v0.0.11

---

python/qianfan/dataset/__init__.py
python/qianfan/dataset/consts.py
python/qianfan/dataset/data_source/__init__.py
python/qianfan/dataset/data_source/afs.py
python/qianfan/dataset/data_source/bos.py
python/qianfan/dataset/data_source/utils.py
python/qianfan/dataset/dataset.py
python/qianfan/resources/batch_inference/helper/helper.py
python/qianfan/resources/llm/chat_completion.py
python/qianfan/utils/fake_pyarrow/__init__.py

+ 增加了 `AFSDataSource`
+ 添加了关于未安装 `pyarrow` 时的警告
+ 兼容 `enable_reading_buffer` 参数并且警告弃用

Afs datasource

---

go/qianfan/model_endpoint_retriever.go
go/qianfan/text2img.go

- **Description:** text2img model panic when using ak/sk
- **Issue:** fix #740 

fix: text2img model list not working

---

python/qianfan/dataset/stress_test/load_statistics.py

- **Description:** 修复报告读取中指标倒置的问题
- **Issue:** 

修复压测指标倒置的问题

---

python/qianfan/common/client/chat.py

- **Description:** 修复cli chat没有正确显示延迟的问题
- **Issue:** /

fix: 修复cli chat没有正确显示延迟的问题

---

java/README.md
java/example/pom.xml
java/pom.xml
java/src/main/java/com/baidubce/qianfan/QianfanClient.java
java/src/main/java/com/baidubce/qianfan/core/builder/ChatBuilder.java
java/src/main/java/com/baidubce/qianfan/model/chat/ChatRequest.java

- **Description:** add inference parameters to chat completion
- **Tag maintainer:** @danielhjz

feat: add inference parameters to chat completion

---

python/qianfan/resources/requestor/base.py
python/qianfan/resources/requestor/openapi_requestor.py

- **Description:** 修复response中的retry config不正确的问题
- **Issue:** /

fix: 修复response中的retry config不正确的问题

---

cookbook/agents/multi-agent-collaboration.ipynb
python/qianfan/common/client/main.py
python/qianfan/resources/llm/chat_completion.py
python/qianfan/resources/llm/function.py

- 修复chat.do传入model='ERNIE-Functions-8K' 失效的问题。
- 新增langgraph 多agent cookbook

fix: support chat.do call model as param & 新增langgraph 多agent cookbook

---

docs/javascript/console.md
javascript/.eslintrc.cjs
javascript/src/utils.ts

- **Description:** consoleApi V1签名问题, 
- **Issue:** the issue # 769,

fix: consoleApi V1签名&API错误捕获

---

javascript/README.md
javascript/examples/langchainChat.ts
javascript/examples/langchainEmbedding.ts

- **Description**: 更新readme，并在examples里添加通过langchain.js使用sdk的示例
- **Tag Container**: @wangting829, @mondaylab, @dl102306

feat: update readme, and add some cases

---

docs/javascript/console.md
javascript/src/utils.ts

- **Dependencies:** 兼容base_api_route,
- **Tag maintainer:** @wangting829 @dl102306 @zpnaruto

feat:兼容base_api_route

---

python/qianfan/resources/console/data.py
python/qianfan/resources/console/finetune.py
python/qianfan/resources/console/model.py
python/qianfan/resources/console/service.py

- **Description:** 修复管控API list调用

fix: llm console page list api marker param

---

javascript/src/Base/index.ts
javascript/src/utils.ts

- **Description:**  iam鉴权不支持模型调用(最新模型未走动态模型拉取), 
- **Issue:** the issue #754,

fix: iam鉴权不支持模型调用

---

javascript/package.json

- **Description:** 更新版本号, 
- **Issue:** the issue #781 ,

fix: Update package.json

---

python/qianfan/tests/chat_completion_test.py

fix: adapt message ut

---

python/qianfan/resources/requestor/base.py
python/qianfan/resources/requestor/openapi_requestor.py

fix: 适配ark usage返回null

---

docs/trainer.md
python/qianfan/tests/trainer_test.py
python/qianfan/trainer/actions.py
python/qianfan/trainer/configs.py

- **Description:** 支持trainer创建训练任务灵活传参&支持resource_config

feat: 支持trainer创建训练任务灵活传参&支持resource_config

---

javascript/.gitignore
javascript/index.d.ts

- **Description:** 修复类型未正确显示的问题, 
- **Issue:** the issue #843  ,
- **Tag maintainer:** @wangting829 @dl102306

fix:修复类型未正确回显问题

---

javascript/package.json
javascript/tsconfig.json

bugfix: js 配置更新

---

go/qianfan/requestor.go

在序列化结构体时去除 RawResponse 字段
