baidubce/bce-qianfan-sdk

src/qianfan/resources/requestor/base.py, src/qianfan/resources/requestor/openapi_requestor.py
- **Description:** move rate limiter to `BaseAPIRequestor`
- **Issue:** #72 
- **Dependencies:** None
=> refactor: move rate limiter location

src/qianfan/dataset/__init__.py, src/qianfan/dataset/data_source.py, src/qianfan/dataset/dataset.py, src/qianfan/dataset/process_interface.py, src/qianfan/dataset/schema.py, src/qianfan/dataset/table.py, src/qianfan/dataset/utils.py, src/qianfan/resources/requestor/base.py, src/qianfan/tests/dataset/dataset_test.py, src/qianfan/tests/dataset/table_test.py, src/qianfan/tests/trainer_test.py
- 新功能：
- Dataset 同时支持数组模式表示与 Table 模式表示
- 新增 Insert 函数
- 支持用户额外传递私有 BOS 配置，中转上传数据集到公共 BOS 数据集中
- 支持直接从 BOS 文件创建并导入数据集
- 自动 Group ID 压缩与重排
- Schema 校验失败时，现提供官方格式示例地址
- 可以使用 `len()` 方法获取 Dataset 内数据的数量
- Bug Fix:
- 修复了当目的文件路径不存在时导出失败的问题
- 修复了 `col_append` 可添加相同列名新列的问题
- 从 Table 与 Dataset 中移除了 `pydantic.BaseModel`
- 增加了更多单测
- 其它:
- 优化 `requestor` 的错误信息
关联 Issue:
#91 #97 #98 #100 #101
=> feat: support two different dataset format

docs/tool.md
=> docs: create tool doc

pyproject.toml, src/qianfan/common/tool/base_tool.py, src/qianfan/config.py, src/qianfan/dataset/data_operator.py, src/qianfan/dataset/data_source.py, src/qianfan/dataset/dataset.py, src/qianfan/dataset/table.py, src/qianfan/evaluation/evaluation_manager.py, src/qianfan/evaluation/evaluator.py, src/qianfan/extensions/langchain/agents/baidu_qianfan_endpoint.py, src/qianfan/model/configs.py, src/qianfan/pydantic.py, src/qianfan/pydantic/__init__.py, src/qianfan/tests/config_test.py, src/qianfan/tests/dataset/dataset_test.py, src/qianfan/tests/tool_test.py, src/qianfan/trainer/configs.py
- **Description:** 为 SDK 提供了 Pydantic V1 的兼容性，现在 SDK 同时支持 Pydantic V1 与 V2
- **Issue:** #177 ,
- **Dependencies:** python-dotenv = "<=0.21.1",
- **Tag maintainer:** @stonekim, @danielhjz, @ZingLix
=> feat: compatible with pydantic v1

src/qianfan/common/client/chat.py
- **Description:** 修复流式返回只有一条消息时，client不显示结果
- **Issue:** /
=> fix: client not showing message when only one response

docs/cli.md, src/qianfan/common/client/chat.py, src/qianfan/common/client/main.py, src/qianfan/common/client/plugin.py, src/qianfan/common/client/utils.py, src/qianfan/resources/llm/base.py
- **Description:** Client 支持插件对话和重置对话，新增 extra_parameters 参数
- **Issue:** #235 
=> feat: support qianfan plugin & reset conversation in client

python/qianfan/common/client/chat.py, python/qianfan/common/client/completion.py, python/qianfan/common/client/dataset.py, python/qianfan/common/client/evaluation.py, python/qianfan/common/client/main.py, python/qianfan/common/client/plugin.py, python/qianfan/common/client/trainer.py, python/qianfan/common/client/utils.py, python/qianfan/consts.py, python/qianfan/model/model.py, python/qianfan/resources/console/finetune.py, python/qianfan/tests/trainer_test.py, python/qianfan/tests/utils/mock_server.py, python/qianfan/trainer/actions.py, python/qianfan/trainer/base.py, python/qianfan/trainer/configs.py, python/qianfan/trainer/finetune.py, python/qianfan/trainer/post_pretrain.py, python/qianfan/utils/logging.py
- **Description:** client 支持 postpretrain
- **Issue:** #246 
=> feat: suppport postpretrain in client

docs/cli.md, python/qianfan/common/client/evaluation.py
- **Description:** 打印可评估模型时支持过滤
- **Issue:** #267 
=> feat: support filter when printing evaluable models

cookbook/auto_truncate_msg.ipynb, python/qianfan/resources/llm/chat_completion.py, python/qianfan/tests/chat_completion_test.py
- **Description:** 默认不启用自动截断过长消息，并增加cookbook
- **Issue:** #303 
=> fix: disable default auto truncate overlong messages

python/qianfan/autotuner/runner/qianfan_runner.py, python/qianfan/common/prompt/prompt.py
- **Description:** identifier 不是 {} 时优化会报错
- **Issue:** #417 
=> fix: prompt optimize not working when identifier is not {}

.github/workflows/py_ci.yml
- **Description:** macos-latest 指向 macos14，用的是 m1，不支持3.9以前的版本
- **Issue:** /
=> fix: python ci workflow not working on macos

java/src/main/java/com/baidubce/qianfan/Qianfan.java, java/src/main/java/com/baidubce/qianfan/core/ModelEndpointRetriever.java, java/src/main/java/com/baidubce/qianfan/core/builder/RerankBuilder.java, java/src/main/java/com/baidubce/qianfan/model/constant/ModelType.java, java/src/main/java/com/baidubce/qianfan/model/rerank/RerankData.java, java/src/main/java/com/baidubce/qianfan/model/rerank/RerankRequest.java, java/src/main/java/com/baidubce/qianfan/model/rerank/RerankResponse.java, java/src/main/java/com/baidubce/qianfan/model/rerank/RerankUsage.java
- **Description:** add reranker support
=> feat: add reranker support

go/qianfan/chat_completion.go, go/qianfan/config.go, go/qianfan/tokenizer.go
Go SDK 添加 `Tokenizer` 并且支持 `ChatCompletion` 的 `Messages` 截断逻辑
=> feat: Go SDK 添加 `Tokenizer` 并且支持 `ChatCompletion` 的 `Messages` 截断逻辑

java/README.md, java/example/pom.xml, java/example/src/main/java/com/baidubce/PluginExample.java, java/pom.xml, java/src/main/java/com/baidubce/qianfan/QianfanClient.java, java/src/main/java/com/baidubce/qianfan/core/ModelEndpointRetriever.java
- **Description:** bump version to 0.0.8 & update model list
- **Tag maintainer:** @danielhjz
=> chore: bump version to 0.0.8 & update model list

java/src/main/java/com/baidubce/qianfan/core/StreamIterator.java, java/src/main/java/com/baidubce/qianfan/util/http/SSEIterator.java
- **Description:** refactor: silently close stream iterator, no need to throw IOException.
=> refactor: silently close stream iterator

javascript/package.json, javascript/src/Base/index.ts, javascript/src/ChatCompletion/index.ts, javascript/src/Completions/index.ts, javascript/src/DynamicModelEndpoint/index.ts, javascript/src/Embedding/index.ts, javascript/src/Images/image2text.ts, javascript/src/Images/text2image.ts, javascript/src/Plugin/index.ts, javascript/src/Reranker/index.ts, javascript/src/streaming/index.ts, javascript/src/utils.ts, javascript/yarn.lock
- **Description:** 浏览器支持自主鉴权和proxy, 
- **Issue:** the issue #681,
=> 浏览器支持自主鉴权和proxy, 

go/qianfan/auth.go, go/qianfan/auth_test.go, go/qianfan/config.go, go/qianfan/console_action.go, go/qianfan/console_action_test.go, go/qianfan/logger.go, go/qianfan/requestor.go, go/qianfan/version.go
=> Feat console call

java/README.md, java/example/pom.xml, java/example/src/main/java/com/baidubce/ConsoleExample.java, java/example/src/main/java/com/baidubce/SystemMemoryExample.java, java/pom.xml, java/src/main/java/com/baidubce/qianfan/Qianfan.java, java/src/main/java/com/baidubce/qianfan/QianfanClient.java, java/src/main/java/com/baidubce/qianfan/core/StreamIterator.java, java/src/main/java/com/baidubce/qianfan/core/builder/ConsoleBuilder.java, java/src/main/java/com/baidubce/qianfan/model/console/ConsoleRequest.java, java/src/main/java/com/baidubce/qianfan/util/CollUtils.java, java/src/main/java/com/baidubce/qianfan/util/Json.java, java/src/main/java/com/baidubce/qianfan/util/ParameterizedTypeImpl.java
- **Description:** add support for qianfan console api calls
- **Issue:** #712 
- **Tag maintainer:** @danielhjz
=> feat: add support for qianfan console api calls

python/qianfan/fake_pyarrow_replacer.py
- **Description:** 修复了`python/qianfan/fake_pyarrow_replacer.py`中`_ModuleFinder`的bug
- **Issue:**: #575 
- **Dependencies:**: Nonebot2
- **Tag maintainer:**: @stonekim @danielhjz @ZingLix @Dobiichi-Origami 
修改了`python/qianfan/fake_pyarrow_replacer.py`中_ModuleFinder，让`_ModuleFinder.find_spec`在大部分情况下返回`None`，避免其阻碍其他模块注册的`MetaPathFinder`
由于`nonebot2`也注册了一个`MetaPathFinder`用于加载`nonebot2`插件，与`qianfan`当前的`_ModuleFinder`冲突，修复这个问题可以让`nonebot2`与`qianfan`兼容。@StarsetNight #575 
请仔细检查我的修改有没有对`_ModuleFinder`的原有功能造成破坏，我对此不确定。
=> fix: _ModuleFinder会阻碍其他MetaPathFinder运行

python/qianfan/extensions/openai/adapter.py
- **Description:** 新增usage
- **Issue:** https://github.com/baidubce/bce-qianfan-sdk/issues/836
=> openai适配器支持usage

go/qianfan/auth.go, go/qianfan/chat_completion_v2.go, go/qianfan/config.go, go/qianfan/requestor.go
- **Description:** 支持 v2 api
- **Issue:**  /
=> feat: go 支持 v2 api

python/qianfan/dataset/stress_test/qianfan_llm_load.py
- **Description:** 新增choices的content合并
- **Issue:** 
=> 补齐query_result中的choices字段

docs/inference.md
Replace this entire comment with:
- **Description:** 补充了文档示例中获取 Bearer token 的示例中 IAM 对象的导入路径
- **Tag maintainer:** @stonekim 
文档中没有提到示例中的 IAM 对象导入路径，用起来得翻找代码，给他补上一行方复制示例代码出来直接用。
=> doc: 补充获取 Bearer token 的示例中 IAM 对象的导入路径
